name: main

on: 
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main

jobs: 
  build-net:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: Create Build Directory
        run: mkdir dist

      - name: Build
        run: dotnet publish SourcetrailCSharpIndexer\SourcetrailCSharpIndexer.csproj -c Release -o "dist" -r win-x64 --nologo --self-contained false

      - name: Packing artifact
        run: |
          7z a SourcetrailCSharpIndexer-win-x64.zip .\dist\*

      - name: Uploading artifacts
        uses: actions/upload-artifact@v2
        with:
          name: BUILD
          path: ./*-win-x64.zip

  release:
    runs-on: ubuntu-latest
    needs: build-net
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - name: Create github release 
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          draft: ${{ !startsWith(github.ref, 'refs/tags/v') }}
          prerelease: false

      - uses: actions/download-artifact@v2
        id: download
        with:
          name: BUILD
          path: ./BUILD

      - name: 'Echo download path'
        if: env.ACTIONS_STEP_DEBUG 
        run: echo ${{steps.download.outputs.download-path}}

      - name: Uploading artifacts to release
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: ${{ steps.download.outputs.download-path }}
          release_id: ${{ steps.create_release.outputs.id }}
          overwrite: true
          verbose: env.ACTIONS_STEP_DEBUG
